In [478]:
import pandas as pd
import numpy as np

In [479]:
df = pd.read_csv('../datasets/Restaurant_Reviews.tsv', sep='\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [480]:
df['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [481]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [482]:
df['Review'] = df['Review'].str.strip()

In [483]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [484]:
df['Review'] = df['Review'].str.lower()

In [485]:
df.head()

Review  Liked
0                           wow... loved this place.      1
1                                 crust is not good.      0
2          not tasty and the texture was just nasty.      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [486]:
import contractions
df['Review'] = df['Review'].apply((contractions.fix))

In [487]:
import string
df['Review'] = df['Review'].str.translate(str.maketrans('', '', string.punctuation))

In [488]:
df.head()

Review  Liked
0                               wow loved this place      1
1                                  crust is not good      0
2           not tasty and the texture was just nasty      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [489]:
df.sample(10)

Review  Liked
950         it was not busy at all and now we know why      0
154         some highlights  great quality nigiri here      1
204                   service is friendly and inviting      1
422  furthermore you cannot even find hours of oper...      0
247  much better than the other ayce sushi place i ...      1
812  this place is overpriced not consistent with t...      0
318  and considering the two of us left there very ...      1
180  the burger had absolutely no flavor  the meat ...      0
818  it kept getting worse and worse so now i am of...      0
205                               very good lunch spot      1

In [490]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
default_stopwords = set(ENGLISH_STOP_WORDS)
words_to_remove = {'not'}
modified_stopwords = default_stopwords - words_to_remove
modified_stopwords_array = list(modified_stopwords)

In [491]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words = modified_stopwords_array,min_df=2)
count_vector = cv.fit_transform(df['Review'])

In [492]:
dense_array = count_vector.toarray()
print(dense_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [493]:
count_vector.shape

(1000, 667)

In [494]:
cv.stop_words

['fill',
 'his',
 'before',
 'third',
 'such',
 're',
 'will',
 'upon',
 'nowhere',
 'who',
 'everything',
 'himself',
 'many',
 'anyway',
 'now',
 'none',
 'hence',
 'herself',
 'thereupon',
 'fire',
 'wherever',
 'eleven',
 'been',
 'it',
 'her',
 'noone',
 'etc',
 'may',
 'next',
 'too',
 'becoming',
 'whatever',
 'back',
 'further',
 'hasnt',
 'while',
 'each',
 'cannot',
 'where',
 'system',
 'which',
 'below',
 'ourselves',
 'most',
 'must',
 'several',
 'whole',
 'be',
 'name',
 'seemed',
 'afterwards',
 'seem',
 'towards',
 'twenty',
 'indeed',
 'find',
 'he',
 'might',
 'you',
 'can',
 'as',
 'no',
 'between',
 'another',
 'anyone',
 'have',
 'from',
 'show',
 'perhaps',
 'though',
 'whereupon',
 'give',
 'yourself',
 'hereafter',
 'being',
 'their',
 'the',
 'they',
 'whence',
 'toward',
 'us',
 'somehow',
 'become',
 'cant',
 'never',
 'cry',
 'ten',
 'anywhere',
 'four',
 'last',
 'con',
 'them',
 'behind',
 'only',
 'anything',
 'go',
 'except',
 'any',
 'same',
 'there',


In [495]:
stop_words = cv.get_stop_words()
print(stop_words)

frozenset({'third', 'before', 'his', 'such', 'will', 're', 'everything', 'many', 'anyway', 'hence', 'herself', 'thereupon', 'eleven', 'been', 'her', 'etc', 'may', 'too', 'whatever', 'back', 'further', 'system', 'which', 'below', 'most', 'several', 'be', 'name', 'seemed', 'twenty', 'indeed', 'find', 'he', 'might', 'you', 'no', 'between', 'have', 'from', 'show', 'perhaps', 'whereupon', 'yourself', 'hereafter', 'being', 'the', 'us', 'cant', 'never', 'cry', 'last', 'them', 'any', 'same', 'becomes', 'made', 'she', 'all', 'alone', 'de', 'nor', 'get', 'latter', 'put', 'why', 'then', 'fifty', 'am', 'over', 'rather', 'whither', 'found', 'him', 'me', 'five', 'should', 'otherwise', 'interest', 'when', 'into', 'yours', 'in', 'done', 'amount', 'its', 'themselves', 'at', 'throughout', 'are', 'since', 'one', 'thence', 'herein', 'couldnt', 'former', 'forty', 'to', 'down', 'bottom', 'ie', 'our', 'yet', 'up', 'others', 'per', 'those', 'namely', 'side', 'until', 'along', 'even', 'was', 'move', 'around', 

In [496]:
if 'not' in stop_words:
    print('Yes')
else:
    print("No")

No


In [497]:
stop_words

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [498]:
filtered_words = []

for review in df['Review']:
    words = review.split()
    for word in words:
        if word not in modified_stopwords:
            filtered_words.append(word)

In [499]:
filtered_words

['wow',
 'loved',
 'place',
 'crust',
 'not',
 'good',
 'not',
 'tasty',
 'texture',
 'just',
 'nasty',
 'stopped',
 'late',
 'bank',
 'holiday',
 'rick',
 'steve',
 'recommendation',
 'loved',
 'selection',
 'menu',
 'great',
 'prices',
 'getting',
 'angry',
 'want',
 'damn',
 'pho',
 'honeslty',
 'did',
 'not',
 'taste',
 'fresh',
 'potatoes',
 'like',
 'rubber',
 'tell',
 'ahead',
 'time',
 'kept',
 'warmer',
 'fries',
 'great',
 'great',
 'touch',
 'service',
 'prompt',
 'not',
 'cashier',
 'care',
 'say',
 'ended',
 'wayyy',
 'overpriced',
 'tried',
 'cape',
 'cod',
 'ravoli',
 'chicken',
 'cranberrymmmm',
 'disgusted',
 'pretty',
 'sure',
 'human',
 'hair',
 'shocked',
 'signs',
 'indicate',
 'cash',
 'highly',
 'recommended',
 'waitress',
 'little',
 'slow',
 'service',
 'place',
 'not',
 'worth',
 'time',
 'let',
 'vegas',
 'did',
 'not',
 'like',
 'burrittos',
 'blah',
 'food',
 'amazing',
 'service',
 'cute',
 'care',
 'interior',
 'just',
 'beautiful',
 'performed',
 'rightt

In [500]:
filtered_words_series = pd.Series(filtered_words)
word_counts = filtered_words_series.value_counts()
filtered_words_min_freq = word_counts[word_counts >= 2].index.tolist()

In [501]:
len(filtered_words_min_freq)

686

In [502]:
filtered_words_min_freq

['not',
 'food',
 'place',
 'good',
 'service',
 'great',
 'like',
 'time',
 'really',
 'did',
 'just',
 'best',
 'friendly',
 'restaurant',
 'nice',
 'amazing',
 'delicious',
 'vegas',
 'experience',
 'came',
 'minutes',
 'disappointed',
 'love',
 'pretty',
 'eat',
 'staff',
 'bad',
 'going',
 'got',
 'definitely',
 'chicken',
 'say',
 'better',
 'think',
 'salad',
 'pizza',
 'stars',
 'menu',
 'wait',
 'worst',
 'way',
 'steak',
 'fresh',
 'ordered',
 'want',
 'quality',
 'flavor',
 'server',
 'taste',
 'sushi',
 'times',
 'burger',
 'night',
 'awesome',
 'fantastic',
 'went',
 'buffet',
 'feel',
 'bland',
 'recommend',
 'come',
 'slow',
 'meal',
 'tasty',
 'know',
 'order',
 'sauce',
 'excellent',
 'waited',
 'little',
 'probably',
 'loved',
 'terrible',
 'coming',
 'prices',
 'atmosphere',
 'selection',
 'perfect',
 'worth',
 'table',
 'breakfast',
 'soon',
 'day',
 'cold',
 'lunch',
 'clean',
 'sandwich',
 'people',
 'meat',
 'hot',
 'fries',
 'dishes',
 'felt',
 'try',
 'tasted',

In [503]:
binary_feature_matrix = pd.DataFrame(0, index=df.index, columns=filtered_words_min_freq)
binary_feature_matrix

not  food  place  good  service  great  like  time  really  did  ...  \
0      0     0      0     0        0      0     0     0       0    0  ...   
1      0     0      0     0        0      0     0     0       0    0  ...   
2      0     0      0     0        0      0     0     0       0    0  ...   
3      0     0      0     0        0      0     0     0       0    0  ...   
4      0     0      0     0        0      0     0     0       0    0  ...   
..   ...   ...    ...   ...      ...    ...   ...   ...     ...  ...  ...   
995    0     0      0     0        0      0     0     0       0    0  ...   
996    0     0      0     0        0      0     0     0       0    0  ...   
997    0     0      0     0        0      0     0     0       0    0  ...   
998    0     0      0     0        0      0     0     0       0    0  ...   
999    0     0      0     0        0      0     0     0       0    0  ...   

     dine  week  end  spend  passed  guy  tuna  pop  selections  bakery  
0       0     0    0      0       0    0     0    0           0       0  
1       0     0    0      0       0    0     0    0           0       0  
2       0     0    0      0       0    0     0    0           0       0  
3       0     0    0      0       0    0     0    0           0       0  
4       0     0    0      0       0    0     0    0           0       0  
..    ...   ...  ...    ...     ...  ...   ...  ...         ...     ...  
995     0     0    0      0       0    0     0    0           0       0  
996     0     0    0      0       0    0     0    0           0       0  
997     0     0    0      0       0    0     0    0           0       0  
998     0     0    0      0       0    0     0    0           0       0  
999     0     0    0      0       0    0     0    0           0       0  

[1000 rows x 686 columns]

In [504]:
for idx, review in enumerate(df['Review']):
    words = set(review.split())
    for word in words:
        if word in filtered_words_min_freq:
            binary_feature_matrix.at[idx, word] = 1

In [505]:
binary_feature_matrix

not  food  place  good  service  great  like  time  really  did  ...  \
0      0     0      1     0        0      0     0     0       0    0  ...   
1      1     0      0     1        0      0     0     0       0    0  ...   
2      1     0      0     0        0      0     0     0       0    0  ...   
3      0     0      0     0        0      0     0     0       0    0  ...   
4      0     0      0     0        0      1     0     0       0    0  ...   
..   ...   ...    ...   ...      ...    ...   ...   ...     ...  ...  ...   
995    0     1      0     0        0      0     0     0       0    0  ...   
996    0     0      0     0        0      0     0     0       0    0  ...   
997    1     0      0     0        0      0     0     0       0    0  ...   
998    0     0      0     0        0      0     0     1       0    0  ...   
999    1     0      0     0        0      0     0     1       0    0  ...   

     dine  week  end  spend  passed  guy  tuna  pop  selections  bakery  
0       0     0    0      0       0    0     0    0           0       0  
1       0     0    0      0       0    0     0    0           0       0  
2       0     0    0      0       0    0     0    0           0       0  
3       0     0    0      0       0    0     0    0           0       0  
4       0     0    0      0       0    0     0    0           0       0  
..    ...   ...  ...    ...     ...  ...   ...  ...         ...     ...  
995     0     0    0      0       0    0     0    0           0       0  
996     0     0    0      0       0    0     0    0           0       0  
997     0     0    0      0       0    0     0    0           0       0  
998     0     0    0      0       0    0     0    0           0       0  
999     0     0    0      0       0    0     0    0           0       0  

[1000 rows x 686 columns]

In [506]:
y = df['Liked']

In [507]:
y

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

In [508]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(binary_feature_matrix, y, test_size=0.2, random_state=42)

In [509]:
log_reg = LogisticRegression()

In [510]:
log_reg.fit(X_train,y_train)

LogisticRegression()

In [511]:
y_pred = log_reg.predict(X_test)

In [512]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
accuracy = accuracy_score(y_test, y_pred)

In [513]:
accuracy * 100 

81.5

In [514]:
precision_score(y_test,y_pred) * 100

86.02150537634408

In [515]:
recall_score(y_test,y_pred) * 100

76.92307692307693