In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../datasets/Restaurant_Reviews.tsv', sep='\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [3]:
df['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [5]:
df['Review'] = df['Review'].str.strip()

In [6]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [7]:
df['Review'] = df['Review'].str.lower()

In [8]:
df.head()

Review  Liked
0                           wow... loved this place.      1
1                                 crust is not good.      0
2          not tasty and the texture was just nasty.      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [9]:
import contractions
df['Review'] = df['Review'].apply((contractions.fix))

In [10]:
import string
df['Review'] = df['Review'].str.translate(str.maketrans('', '', string.punctuation))

In [11]:
df.head()

Review  Liked
0                               wow loved this place      1
1                                  crust is not good      0
2           not tasty and the texture was just nasty      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [12]:
df.sample(10)

Review  Liked
475     third the cheese on my friends burger was cold      0
817     the seasonal fruit was fresh white peach puree      1
963  after all the rave reviews i could not wait to...      0
71                really really good rice all the time      1
383                              the food was terrible      0
749  wonderful lil tapas and the ambience made me f...      1
274         the chefs were friendly and did a good job      1
121  worst service to boot but that is the least of...      0
360  the buffet is small and all the food they offe...      0
862  hot dishes are not hot cold dishes are close t...      0

In [13]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
default_stopwords = set(ENGLISH_STOP_WORDS)
words_to_remove = {'not'}
modified_stopwords = default_stopwords - words_to_remove
modified_stopwords_array = list(modified_stopwords)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words = modified_stopwords_array,min_df=2)
count_vector = cv.fit_transform(df['Review'])

In [15]:
dense_array = count_vector.toarray()
print(dense_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
count_vector.shape

(1000, 667)

In [17]:
cv.stop_words

['bottom',
 'part',
 'she',
 'how',
 'itself',
 'forty',
 'those',
 'hereby',
 'due',
 'someone',
 'other',
 'nobody',
 'onto',
 'now',
 'side',
 'via',
 'among',
 'own',
 'meanwhile',
 'none',
 'or',
 'nowhere',
 'namely',
 'should',
 'several',
 'former',
 'became',
 'first',
 'seeming',
 'name',
 'please',
 'keep',
 'un',
 'these',
 'under',
 'have',
 'was',
 'by',
 'because',
 'myself',
 'wherein',
 'throughout',
 'could',
 'very',
 'whom',
 'found',
 'with',
 'beforehand',
 'next',
 'take',
 'us',
 'only',
 'yourself',
 'nine',
 'an',
 'be',
 'anyway',
 'together',
 'might',
 'if',
 'one',
 'no',
 'already',
 'out',
 'off',
 'empty',
 'beside',
 'whenever',
 'twenty',
 'formerly',
 'often',
 'something',
 'for',
 'amoungst',
 'upon',
 'twelve',
 'whoever',
 'elsewhere',
 'serious',
 'this',
 'amongst',
 'fifty',
 'am',
 'before',
 'than',
 'besides',
 'everywhere',
 'ever',
 'over',
 'whole',
 'cant',
 'below',
 'also',
 'more',
 'which',
 'few',
 'above',
 'whereupon',
 'whither'

In [18]:
stop_words = cv.get_stop_words()
print(stop_words)

frozenset({'how', 'forty', 'those', 'due', 'other', 'nobody', 'now', 'side', 'via', 'own', 'meanwhile', 'none', 'nowhere', 'namely', 'should', 'former', 'first', 'seeming', 'name', 'keep', 'because', 'myself', 'could', 'found', 'with', 'yourself', 'nine', 'an', 'be', 'anyway', 'if', 'out', 'empty', 'whenever', 'twenty', 'something', 'amoungst', 'whoever', 'this', 'amongst', 'am', 'before', 'besides', 'everywhere', 'over', 'whole', 'cant', 'few', 'whither', 'yourselves', 'why', 'fill', 'again', 'system', 'such', 'neither', 'i', 'the', 'himself', 'further', 'mill', 'still', 'we', 'less', 'thin', 'couldnt', 'yet', 'within', 'either', 'rather', 'even', 'hers', 'co', 'well', 'alone', 'perhaps', 'though', 'bill', 'wherever', 'ie', 'thereby', 'becoming', 'latterly', 'can', 'when', 'four', 'hundred', 'third', 'whose', 'detail', 'to', 'whether', 'may', 'your', 'me', 'get', 'everything', 'thick', 'you', 'least', 'mostly', 'put', 'after', 'that', 'anything', 'is', 're', 'what', 'done', 'herein', 

In [19]:
if 'not' in stop_words:
    print('Yes')
else:
    print("No")

No


In [20]:
stop_words

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [21]:
filtered_words = []

for review in df['Review']:
    words = review.split()
    for word in words:
        if word not in modified_stopwords:
            filtered_words.append(word)

In [22]:
filtered_words

['wow',
 'loved',
 'place',
 'crust',
 'not',
 'good',
 'not',
 'tasty',
 'texture',
 'just',
 'nasty',
 'stopped',
 'late',
 'bank',
 'holiday',
 'rick',
 'steve',
 'recommendation',
 'loved',
 'selection',
 'menu',
 'great',
 'prices',
 'getting',
 'angry',
 'want',
 'damn',
 'pho',
 'honeslty',
 'did',
 'not',
 'taste',
 'fresh',
 'potatoes',
 'like',
 'rubber',
 'tell',
 'ahead',
 'time',
 'kept',
 'warmer',
 'fries',
 'great',
 'great',
 'touch',
 'service',
 'prompt',
 'not',
 'cashier',
 'care',
 'say',
 'ended',
 'wayyy',
 'overpriced',
 'tried',
 'cape',
 'cod',
 'ravoli',
 'chicken',
 'cranberrymmmm',
 'disgusted',
 'pretty',
 'sure',
 'human',
 'hair',
 'shocked',
 'signs',
 'indicate',
 'cash',
 'highly',
 'recommended',
 'waitress',
 'little',
 'slow',
 'service',
 'place',
 'not',
 'worth',
 'time',
 'let',
 'vegas',
 'did',
 'not',
 'like',
 'burrittos',
 'blah',
 'food',
 'amazing',
 'service',
 'cute',
 'care',
 'interior',
 'just',
 'beautiful',
 'performed',
 'rightt

In [23]:
filtered_words_series = pd.Series(filtered_words)
word_counts = filtered_words_series.value_counts()
filtered_words_min_freq = word_counts[word_counts >= 2].index.tolist()

In [24]:
len(filtered_words_min_freq)

686

In [25]:
filtered_words_min_freq

['not',
 'food',
 'place',
 'good',
 'service',
 'great',
 'like',
 'time',
 'really',
 'did',
 'just',
 'best',
 'friendly',
 'restaurant',
 'nice',
 'amazing',
 'delicious',
 'vegas',
 'experience',
 'came',
 'minutes',
 'disappointed',
 'love',
 'pretty',
 'eat',
 'staff',
 'bad',
 'going',
 'got',
 'definitely',
 'chicken',
 'say',
 'better',
 'think',
 'salad',
 'pizza',
 'stars',
 'menu',
 'wait',
 'worst',
 'way',
 'steak',
 'fresh',
 'ordered',
 'want',
 'quality',
 'flavor',
 'server',
 'taste',
 'sushi',
 'times',
 'burger',
 'night',
 'awesome',
 'fantastic',
 'went',
 'buffet',
 'feel',
 'bland',
 'recommend',
 'come',
 'slow',
 'meal',
 'tasty',
 'know',
 'order',
 'sauce',
 'excellent',
 'waited',
 'little',
 'probably',
 'loved',
 'terrible',
 'coming',
 'prices',
 'atmosphere',
 'selection',
 'perfect',
 'worth',
 'table',
 'breakfast',
 'soon',
 'day',
 'cold',
 'lunch',
 'clean',
 'sandwich',
 'people',
 'meat',
 'hot',
 'fries',
 'dishes',
 'felt',
 'try',
 'tasted',

In [26]:
binary_feature_matrix = pd.DataFrame(0, index=df.index, columns=filtered_words_min_freq)
binary_feature_matrix

not  food  place  good  service  great  like  time  really  did  ...  \
0      0     0      0     0        0      0     0     0       0    0  ...   
1      0     0      0     0        0      0     0     0       0    0  ...   
2      0     0      0     0        0      0     0     0       0    0  ...   
3      0     0      0     0        0      0     0     0       0    0  ...   
4      0     0      0     0        0      0     0     0       0    0  ...   
..   ...   ...    ...   ...      ...    ...   ...   ...     ...  ...  ...   
995    0     0      0     0        0      0     0     0       0    0  ...   
996    0     0      0     0        0      0     0     0       0    0  ...   
997    0     0      0     0        0      0     0     0       0    0  ...   
998    0     0      0     0        0      0     0     0       0    0  ...   
999    0     0      0     0        0      0     0     0       0    0  ...   

     dine  week  end  spend  passed  guy  tuna  pop  selections  bakery  
0       0     0    0      0       0    0     0    0           0       0  
1       0     0    0      0       0    0     0    0           0       0  
2       0     0    0      0       0    0     0    0           0       0  
3       0     0    0      0       0    0     0    0           0       0  
4       0     0    0      0       0    0     0    0           0       0  
..    ...   ...  ...    ...     ...  ...   ...  ...         ...     ...  
995     0     0    0      0       0    0     0    0           0       0  
996     0     0    0      0       0    0     0    0           0       0  
997     0     0    0      0       0    0     0    0           0       0  
998     0     0    0      0       0    0     0    0           0       0  
999     0     0    0      0       0    0     0    0           0       0  

[1000 rows x 686 columns]

In [27]:
for idx, review in enumerate(df['Review']):
    words = set(review.split())
    for word in words:
        if word in filtered_words_min_freq:
            binary_feature_matrix.at[idx, word] = 1

In [28]:
binary_feature_matrix

not  food  place  good  service  great  like  time  really  did  ...  \
0      0     0      1     0        0      0     0     0       0    0  ...   
1      1     0      0     1        0      0     0     0       0    0  ...   
2      1     0      0     0        0      0     0     0       0    0  ...   
3      0     0      0     0        0      0     0     0       0    0  ...   
4      0     0      0     0        0      1     0     0       0    0  ...   
..   ...   ...    ...   ...      ...    ...   ...   ...     ...  ...  ...   
995    0     1      0     0        0      0     0     0       0    0  ...   
996    0     0      0     0        0      0     0     0       0    0  ...   
997    1     0      0     0        0      0     0     0       0    0  ...   
998    0     0      0     0        0      0     0     1       0    0  ...   
999    1     0      0     0        0      0     0     1       0    0  ...   

     dine  week  end  spend  passed  guy  tuna  pop  selections  bakery  
0       0     0    0      0       0    0     0    0           0       0  
1       0     0    0      0       0    0     0    0           0       0  
2       0     0    0      0       0    0     0    0           0       0  
3       0     0    0      0       0    0     0    0           0       0  
4       0     0    0      0       0    0     0    0           0       0  
..    ...   ...  ...    ...     ...  ...   ...  ...         ...     ...  
995     0     0    0      0       0    0     0    0           0       0  
996     0     0    0      0       0    0     0    0           0       0  
997     0     0    0      0       0    0     0    0           0       0  
998     0     0    0      0       0    0     0    0           0       0  
999     0     0    0      0       0    0     0    0           0       0  

[1000 rows x 686 columns]

In [29]:
y = df['Liked']

In [30]:
y

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(binary_feature_matrix, y, test_size=0.2, random_state=42)

In [32]:
X_test

not  food  place  good  service  great  like  time  really  did  ...  \
521    1     0      0     0        0      0     0     0       0    0  ...   
737    0     1      0     0        1      0     0     0       0    0  ...   
740    0     0      0     0        0      0     0     0       0    0  ...   
660    0     0      0     0        0      0     0     0       0    0  ...   
411    0     0      0     0        0      0     0     0       0    0  ...   
..   ...   ...    ...   ...      ...    ...   ...   ...     ...  ...  ...   
408    0     0      0     0        1      0     0     0       0    0  ...   
332    0     0      0     0        1      0     0     0       0    0  ...   
208    0     0      1     0        0      0     0     0       0    0  ...   
613    1     1      0     0        0      0     0     0       0    0  ...   
78     0     0      0     1        0      0     0     1       0    0  ...   

     dine  week  end  spend  passed  guy  tuna  pop  selections  bakery  
521     0     0    0      0       0    0     0    0           0       0  
737     0     0    0      0       0    0     0    0           0       0  
740     0     0    0      0       0    0     0    0           0       0  
660     0     0    0      0       0    0     0    0           0       0  
411     0     0    0      0       0    0     0    0           0       0  
..    ...   ...  ...    ...     ...  ...   ...  ...         ...     ...  
408     0     0    0      0       0    0     0    0           0       0  
332     0     0    0      0       0    0     0    0           0       0  
208     0     0    0      0       0    0     0    0           0       0  
613     0     0    0      0       0    0     0    0           0       0  
78      0     0    0      0       0    0     0    0           0       0  

[200 rows x 686 columns]

In [33]:
log_reg = LogisticRegression()

In [34]:
log_reg.fit(X_train,y_train)

LogisticRegression()

In [35]:
y_pred = log_reg.predict(X_test)

In [36]:
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1])

In [37]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
accuracy = accuracy_score(y_test, y_pred)

In [38]:
accuracy * 100 

81.5

In [39]:
precision_score(y_test,y_pred) * 100

86.02150537634408

In [40]:
recall_score(y_test,y_pred) * 100

76.92307692307693

In [41]:
binary_feature_matrix.columns

Index(['not', 'food', 'place', 'good', 'service', 'great', 'like', 'time',
       'really', 'did',
       ...
       'dine', 'week', 'end', 'spend', 'passed', 'guy', 'tuna', 'pop',
       'selections', 'bakery'],
      dtype='object', length=686)

In [42]:
dict = {}
for index in binary_feature_matrix.columns:
    dict[index] = 0
dict

{'not': 0,
 'food': 0,
 'place': 0,
 'good': 0,
 'service': 0,
 'great': 0,
 'like': 0,
 'time': 0,
 'really': 0,
 'did': 0,
 'just': 0,
 'best': 0,
 'friendly': 0,
 'restaurant': 0,
 'nice': 0,
 'amazing': 0,
 'delicious': 0,
 'vegas': 0,
 'experience': 0,
 'came': 0,
 'minutes': 0,
 'disappointed': 0,
 'love': 0,
 'pretty': 0,
 'eat': 0,
 'staff': 0,
 'bad': 0,
 'going': 0,
 'got': 0,
 'definitely': 0,
 'chicken': 0,
 'say': 0,
 'better': 0,
 'think': 0,
 'salad': 0,
 'pizza': 0,
 'stars': 0,
 'menu': 0,
 'wait': 0,
 'worst': 0,
 'way': 0,
 'steak': 0,
 'fresh': 0,
 'ordered': 0,
 'want': 0,
 'quality': 0,
 'flavor': 0,
 'server': 0,
 'taste': 0,
 'sushi': 0,
 'times': 0,
 'burger': 0,
 'night': 0,
 'awesome': 0,
 'fantastic': 0,
 'went': 0,
 'buffet': 0,
 'feel': 0,
 'bland': 0,
 'recommend': 0,
 'come': 0,
 'slow': 0,
 'meal': 0,
 'tasty': 0,
 'know': 0,
 'order': 0,
 'sauce': 0,
 'excellent': 0,
 'waited': 0,
 'little': 0,
 'probably': 0,
 'loved': 0,
 'terrible': 0,
 'coming': 0,

In [43]:
type(X_test.iloc[0])

pandas.core.series.Series

In [44]:
str = "the food is tasty"

In [45]:
input_data = pd.Series(data=np.zeros(X_test.columns.shape[0]), index=X_test.columns,dtype='int32')
input_data

not           0
food          0
place         0
good          0
service       0
             ..
guy           0
tuna          0
pop           0
selections    0
bakery        0
Length: 686, dtype: int32

In [46]:
for word in str.split():
    if word in X_test.columns:
        input_data[word] = 1
        
log_reg.predict([input_data])[0]

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


1

In [47]:
def prediction(review):
    review = review.strip()
    review = review.lower()
    review = contractions.fix(review)
    review = review.translate(str.maketrans('', '', string.punctuation))
    print(contractions)
    input_data = pd.Series(data=np.zeros(X_test.columns.shape[0]), index=filtered_words_min_freq,dtype='int32')
    for word in review.split():
        if word in X_test.columns:
            input_data[word] = 1
    
    return log_reg.predict([input_data])[0]

In [48]:
prediction("This food is awesome!")

<module 'contractions' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/contractions/__init__.py'>


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


1